### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by brockallen** [thinktecture/Thinktecture.IdentityServer.v3#249]
Figure out how we're going to do 2FA -- do we force a custom user service, or do we extend the user service interface to support it.

Comments/Thoughts?

**Comment by sidwall** [comment]
To make it as simple as possible to getting started I vote for extendning the existing service and make it work for MembershipReboot and ASP.NET Identity out-of-the-box.

**Comment by brockallen** [comment]
@sidwall that's almost impossible since they each do it differently.
