### ISSUE TITLE
Sample for PreAuthenticateAsync

### ISSUE THREAD

**Issue by brockallen** [thinktecture/Thinktecture.IdentityServer.v3#483]
Windows auth or client cert

**Comment by brockallen** [comment]
another idea: impersonation

**Comment by leastprivilege** [comment]
moved to samples repo

**Comment by pappnas** [comment]
Hmm, I do not find a sample with Windows Auth...

**Comment by leastprivilege** [comment]
There is none right now.

**Comment by pappnas** [comment]
Do you have a hint, how to get started for this? Perhaps I could create the sample then.

P.S. I didn't find any PreAuthenticateAsync() sample...
