### ISSUE TITLE
Relying party claims mapping "pass through" mode

### ISSUE THREAD

**Issue by DmitryNaumov** [thinktecture/Thinktecture.IdentityServer.v3#510]
I'm using IdentityServer + WsFederation plugin to authenticate users and IdentityManager to manage them and their claims. IdentityManager has nice feature to add any claim to user. But RelyingParty class (Thinktecture.IdentityServer.WsFederation.Models.RelyingParty) has no "pass through" mode for claims mapping. Only claims mentioned in RelyingParty.ClaimMappings dictionary will be present in sign in response. So even added new claims I should change claim mapping via code or configuration.

It would be nice to have, for example, virtual bool TryMapClaim(string, out string) method on RelyingParty which by default uses mappings in RelyingParty, but allows to override and change this behavior.

**Comment by leastprivilege** [comment]
I will add a "pass through" flag on the RP - as well as a standard prefix for claims that are not specifically mapped

**Comment by leastprivilege** [comment]
added on dev branch - will go into RC build later today. thanks!
