### ISSUE TITLE
Automatic login after registration

### ISSUE THREAD

**Issue by marcindzwonnik** [thinktecture/Thinktecture.IdentityServer.v3#638]
Hi,

I read similiar issues which were closed, but they didn't mention my idea.

I plan to extend IS with registration page.
If I copy paste code for login and add logic for creating new account before logging user in. 
It should work, shouldn't it?

**Comment by brockallen** [comment]
You can have your registration issue a cookie of some sort with the newly registered user's subject id (protected in some way of course), then in the user service PreAuthenticate you can use that to trigger a login and avoid showing the login page.

**Comment by brockallen** [comment]
In fact, I'll use this scenario when I do the sample for PreAuthenticate: https://github.com/thinktecture/Thinktecture.IdentityServer.v3/issues/483#issuecomment-68952076

I'll close this issue for now. Watch #483 if/when you're interested in the sample.

**Comment by pappnas** [comment]
Do you have a hint, how to get started for this? Perhaps I could create the sample then.

P.S. I didn't find any PreAuthenticateAsync() sample...
