### ISSUE TITLE
Fully customise IViewService using MVC?

### ISSUE THREAD

**Issue by sparikh9999** [thinktecture/Thinktecture.IdentityServer.v3#645]
Hi

I understand how to customise the IViewService and provide a custom UI for login,logout etc.  But outputting a Stream seems a little limiting.

We have an existing MVC application that has a number of specific requirements - e.g. outputting in hidden html fields info such as 'number of failed logins', 'account status' etc.  Plus there are workflows such as 'Expired Passwords' etc. which have already been implemented.

I'd like to reuse this existing MVC code but integrate IdSrv3 so as to provide an ODP to other applications.

I'd greatly appreciate any advice.

**Comment by leastprivilege** [comment]
it's january ;)

**Comment by imperugo** [comment]
ahahah you are right. I'm working on it in these days, the "problem" is that I dunno so well angular so, I'm figuring out what it does and creating the view server side. Nothing complicated, the PR is on its way :)

**Comment by sparikh9999** [comment]
If its any use - I've got layouts working with Razor Engine too (in a rather hacky fashion).  Am looking into the templating features to see if this can be improved - unless you already have it?  

 protected virtual Task<System.IO.Stream> Render(CommonViewModel model, string page, string clientName = null)
        {
            string layout = LoadHtml(@"Shared\_Layout");
            string html = LoadHtml(page);

            html = layout.Replace(@"@RenderBody()", html);

            var cshtml = Razor.Parse(html, model);
            return Task.FromResult(StringToStream(cshtml));
        }

**Comment by imperugo** [comment]
Hi @sparikh9999 
thanks for the suggestion, I think we can something cool here :+1: I'm trying to cache the html (avoiding to read the file every time) and implement the master page (that's what you did).

Thanks, hope to push something end of week/begin of next one.

**Comment by sparikh2000** [comment]
Looking forward to it @imperugo   Thanks

**Comment by brockallen** [comment]
I'll go ahead and close this issue now. 

Feel free to comment here once the blog post or repo is available for us to check out. Once you do, we can link to it from the docs.

**Comment by senseicz** [comment]
Rather than Razor Engine, take a look at Razor Machine - https://github.com/jlamfers/RazorMachine . This has layout and _viewStart out of the box.
