### ISSUE TITLE
Encoding of special characters in username upon failed authentication

### ISSUE THREAD

**Issue by vanderkleij** [thinktecture/Thinktecture.IdentityServer.v3#649]
Our usernames are in UPN format, that is user@domain.com. If authentication fails, the user is shown the login form again with the username that he just entered. The "@" in the username then shows up as "\x40" however (user\x40domain.com).

This is due to a change in 7c8d92ee66b554f417872750553356c635c54cec that adds encoding of special characters in the username. Any encoding that is performed here is however encoded again in DefaultViewService.cs in BuildModel by SerializeObject. This causes the username to show up as user\x40domain.com.

I believe the fix is to just remove the javascript encoding introduced in 7c8d92ee66b554f417872750553356c635c54cec: any dangerous content in the username should get encoded by SerializeObject later on.

**Comment by AdamDotNet** [comment]
I have downloaded MyGet build 10149 and the @ remains an @ after a failed login as desired. For now though, I'll be sticking to the mainstream Nuget build. Thank you.

**Comment by brockallen** [comment]
We'll be pushing a new NuGet in about a week for RC.
