### ISSUE TITLE
ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType) always null

### ISSUE THREAD

**Issue by mikethedarv** [thinktecture/Thinktecture.IdentityServer.v3#676]
After upgrading to beta-4, it appears as though my external registration flow is not working.  My custom user service returns this for the call to _userService.AuthenticateExternalAsync(externalIdentity);

```
// User not registered so we will issue a partial login and redirect them to our registration page
var principal = IdentityServerPrincipal.Create(providerId, externalName, Constants.AuthenticationMethods.External, provider);
 var claimsIdentity = (ClaimsIdentity)principal.Identity;

claimsIdentity.AddClaim(new Claim(Constants.ClaimTypes.Email, emailAddress));
claimsIdentity.AddClaim(new Claim(Constants.ClaimTypes.GivenName, firstName));
claimsIdentity.AddClaim(new Claim(Constants.ClaimTypes.FamilyName, lastName));

return new AuthenticateResult("/register/external", providerId, externalName, claimsIdentity.Claims, provider);
```

If I step through the AuthenticationController class in the Core project, I can see the call to SignInandRedirect (and subsequently the call to IssueAuthenticationCookie).  Everything appears to be working correctly.  The call to ctx.Authentication.SignIn(props, id); is executed, and after inspecting the identity it is passing, the login type is correctly "idsrv.partial".

However, after that code is reached and it performs the redirect to my registration controller, it fails:

```
// this verifies that we have a prtial signin from idsvr
var ctx = Request.GetOwinContext();
var authentication = await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);

if (authentication == null) {
     return InvalidExternalAuthentication();
}
```

The problem is authentication is always null, as if the cookie is not being set properly or something.

Any help is greatly appreciated!

Thanks,

Mike

**Comment by brockallen** [comment]
Without more debugging or info, I'm not sure how to help.

**Comment by sparikh2000** [comment]
I know this is closed but I get a similar problem using local authentication.

Say I configure idsrv in start up to /core...

if I do a partial login from AuthenticateLocalAsync() and redirect to my custom controller at  /**account**/passwordexpired - I get the same problem as reported above - the idsrv.partial cookie is missing and so ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType) returns null

But, if I redirect to /**core**/passwordexpired instead - it works as expected and I can see the idsrv.partial cookie!
 
Any ideas?

**Comment by brockallen** [comment]
Yes -- you need to set the `Path` on the `CookieOptions`. By default we scope our cookie paths to where IdentityServer is `Map`ped.

**Comment by sparikh2000** [comment]
ok - tried setting the CookieOptions.Path to "/" - but no it still fails

**Comment by brockallen** [comment]
So debug more -- is the cookie passed to the custom page? If so, then perhaps it's a format issue -- meaning the protection is different.

**Comment by sparikh2000** [comment]
Yes the cookie is present in the custom page.  

I can get the same error in the CustomUserService sample using the EulaAtLoginUserService - 

map idsrv to "CoreX", set CookieOptions.Path to "/" and the working example fails just as above in "Core/Eula"

**Comment by brockallen** [comment]
Hmmm, so maybe it is a beta issue? The custom user service samples are working on dev.

**Comment by sparikh2000** [comment]
I've now got the latest beta 4 code and samples, make the above change to the samples code and it fails exactly the same way.

I cant see how I can debug further into the owin context:
Request.GetOwinContext().Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType)

**Comment by brockallen** [comment]
Ok, yes -- so I now see the problem. The issue is that the cookie authentication middleware is not registered at the root of `/` -- it's only under `/core` where IdentityServer is registered. So yea, this is a fundamental restriction -- your paths to the partial redirects must be at the same base path where IdentityServer is registered with Katana. I'm sorry I didn't key into the issue earlier in this thread.

I understand the potential frustration with this, but it's a current limitation. To get configure the cookie middleware outside of the IdentityServer mapped path (with all the right protection configuration) is a pain.

Is it a show stopper to use the `[Route]` mapping in MVC to accept URLs under the IdentityServer mapped path (as the sample is doing)?

**Comment by sparikh2000** [comment]
Thanks @brockallen.  I can live with it now that I understand the limitation.  It causes a minor issue with one of our large customer who use a legacy screen-scraper to read hidden form fields in the response to a successful login. (Dumb I know!) 

So I wanted to be able to emulate this by doing a partial redirect to bla.com/foo/login.  Of course now I cant do this via bla.com/core/login without an infinite loop!!! (their scrapper scans for the string 'login' in the url)

Anyway many thanks for looking into this and clarifying the problem.
