### ISSUE TITLE
URL Fragment code in StringExtensions breaks Identity Manager

### ISSUE THREAD

**Issue by jasonkres** [thinktecture/Thinktecture.IdentityServer.v3#685]
The change 78657c86e17e7721dc2ad782a404fd574a5a37d6 breaks integration with Identity Manager (and potentially other applications).
I am using IdentityServer 1.0.0-beta4-1 and IdentityManager 1.0.0-beta2-1.

In the Identity Manager Host example, the OAuth2 callback URL as in Host/IdSvr/IdSvrConfig.cs is: `http://localhost:17457/idm/#/callback`
However, the newer code `if (!url.Contains("#"))` in StringExtensions.cs to add the fragment detects that the above URL already has a fragment.  This results in a missing separator in the redirect; i.e., 

```
Bad:    http://localhost:17457/idm/#/callbackaccess_token=...
Works:  http://localhost:17457/idm/#/callback#access_token=...
```

The observable effect is that the user is not logged on to the Identity Manager; the user returns to the page with the login button.

I don't know if multiple # signs are allowed by the URI specs.  The problem may ultimately be Identity Manager.

**Comment by brockallen** [comment]
IdentityManager has now been updated (on dev) for these changes
