### ISSUE TITLE
Purging message cookies fails when cookies that can not be decrypted exist

### ISSUE THREAD

**Issue by ca-ta** [thinktecture/Thinktecture.IdentityServer.v3#687]
Purging message cookies fails when at least one cookie exists that was encrypted with a key different from the one used by the current IDataProtector. In this circumstance, the attempt to decrypt the cookie causes an exception to be thrown and results in the user being unable to log in. 
The workaround of deleting the cookies in the browser seems to me unacceptable.

While it is true that one may craft and use a DataProtectionprovider other than the default one (DpapiDataProtectionProvider) and conceivably avoid the issue, I believe the server should be intrinsically resilient to malformed cookies – hence the proposed change (#686).

**Comment by brockallen** [comment]
Merged on dev. thx.

**Comment by ca-ta** [comment]
Awesome - thank you!
