### ISSUE TITLE
post_logout_redirect_uri in implicit client

### ISSUE THREAD

**Issue by stevenfirstrowinc** [thinktecture/Thinktecture.IdentityServer.v3#699]
Hi,

I'm not having much luck getting my post_logout_redirect_uri to work in my implicit client application.  The url differs from the main application (different domain), but I don't see why it wouldn't work.  Here are the relevant details.

client's config

    PostLogoutRedirectUris = new List<string>
    {
        "https://www.microsoft.com"
    },

javascript logout function on the client
    
    $window.location = "https://localhost:44310/identity/logout?id=" + response.id_token + "&post_logout_redirect_uri=https://www.codysoft.net"

nothing in the trace log of id srv
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 12/31/2014 1:31:39 AM -- Logout prompt for subject: raall
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 12/31/2014 1:31:41 AM -- Logout requested for subject: raall
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 12/31/2014 1:31:41 AM -- rendering logged out page
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.EndSessionController]: 12/31/2014 1:31:42 AM -- End session callback requested

I have tried 
id=" + response.id_token 
id_token=" + response.id_token
id_token_hint=" + response.id_token

**Comment by leastprivilege** [comment]
If logout does anything - it's rather a bug.

You need to use the endpoint advertised in the discovery document.
