### ISSUE TITLE
How to combine client authorization with user authorization

### ISSUE THREAD

**Issue by HenkHui** [thinktecture/Thinktecture.IdentityServer.v3#700]
Hi,

I am trying to implement Identity Server v3 for the following scenario:

I am creating a web API which will contain resources (OData based) which will be used by multiple clients. Some clients will be developed by ourselves, however in future scenario's third party clients must also be able to use the API. Therefore I want to be able to restrict access to resources within the API for the clients.
There are also resources which can only be accessed on behalf of the logged in user. The roles of the user determine whether access is allowed. Scopes can be used to check whether the user has authorized the client to access the resource on behalf of the user.
The client will not always call the API in the context of a user. So when the API resource does not need a current user it will be called with an access token obtained by using the client credentials flow. And when it does need a user, it will be called with an access token obtained by using the hybrid flow. In both cases I am using scopes to check for authorization. To make things clearer an example: in the hybrid flow the client asks for the scope "User.read" to be able to read the user information for the logged on user. Whereas in the client credentials flow the client asks for the scope "Content.faq" to be able to get access to the faq resource from the API.
There's no problem implementing the above but when I want to mix things it gets complicated. For example when I want to be able to enforce that only a certain set of faq items can be accessed when the user is not logged in and all faq items can be accessed when the user is logged in (and the faq resource can only be accessed by certain clients).
In this case I would need an access token which contains both user and client authorization information (scopes in my case).
When I demand the "client scopes" in the hybrid flow the user is bothered with these scopes (which are not related to his account) on the consent screen.

The latest version of IdentityServer supports "Client claims" which I could use to configure client scopes. However in issue "Add claims to Client model #549 " @leastprivilege says "client and user authorization are two very different things. I wouldn't mix them.", therefore my questions are:

1. Is it wise to use the new "Client claims" functionality to implement a "mixed client and user authorization scenario"?
2. Is scope based authorization to restrict access to resources in the API the way to go, or should I use roles for this kind of authorization?

**Comment by leastprivilege** [comment]
Scopes are nothing else as identifiers for resources (typically an API or a group of APIs) - either a client can access them per configuration - or not. User authorization (e.g. roles) are orthogonal to that.

When the access token contains a "sub" claim - you know a human was involved - otherwise client credential flow was used.

Client claims are primarily for client credentals flow - where you want e.g. to do authorization based on client identity - but prefer a level of indirection to the client id (e.g. groups of clients).

See also here:
https://speakerdeck.com/leastprivilege/web-api-authorization-and-access-control-done-right-ndc-oslo-2014?slide=42

**Comment by elfarouqy** [comment]
hello can get Role from .net Core Server to MVC5 Asp Client beacause i can't get Role thansk for answer me

**Comment by elfarouqy** [comment]
but in IdentityServer4
