### ISSUE TITLE
Getting 401 Unauthorized with valid access token

### ISSUE THREAD

**Issue by Bala2Excel** [thinktecture/Thinktecture.IdentityServer.v3#703]
Hi, 

I downloaded the latest Thinktecture v3 Identity server along with the Clients source code.

Started the Server Hosts and it is running on port 44333
![image](https://cloud.githubusercontent.com/assets/5871989/5592240/a4767f82-91e8-11e4-90c0-4e19a972d74f.png)

Ran the Javascript Implicit Client Demo and used the valid username and password (in memory service) to get the valid Id/ access token

![image](https://cloud.githubusercontent.com/assets/5871989/5592245/10ea8410-91e9-11e4-833e-2e5e9492a042.png)

![image](https://cloud.githubusercontent.com/assets/5871989/5592248/2951718a-91e9-11e4-9443-f149c73229a4.png)

Now, Clicked on the Call Service button and got 401 error, I noticed the Authorization token being passed in the request.

![image](https://cloud.githubusercontent.com/assets/5871989/5592251/5e3ee9e0-91e9-11e4-8f27-555c337896f5.png)

I couldn't get a clue on the issue. 

Kindly help at the earliest.

**Comment by leastprivilege** [comment]
see here how to enable Katana tracing

https://katanaproject.codeplex.com/wikipage?title=Debugging&referringTitle=Documentation

**Comment by Bala2Excel** [comment]
I enabled Tracing on the service and it seems there is a certificate issue. Am I missing a basic step?

please help!

![image](https://cloud.githubusercontent.com/assets/5871989/5594248/b99eae36-9268-11e4-96c7-3a56acebdd50.png)

**Comment by Bala2Excel** [comment]
I followed the link https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/tree/master/source/Certificates

and installed Certificates. Still having the same issue! is there any other guide which I need to follow? or is there a way for me to verify whether I have installed certificates correctly.

![image](https://cloud.githubusercontent.com/assets/5871989/5594338/30d10314-926e-11e4-9cb7-511b465cd1b0.png)

**Comment by brockallen** [comment]
I was able to reproduce this. I suspect it's a bug in the JS. I'll look into it.

**Comment by brockallen** [comment]
Oh sorry -- I was mistaken (user error). It's is working for me.

**Comment by brockallen** [comment]
Ok, your error indicates that the SSL cert IdentityServer is using is not trusted for the token validation from the Web API project to IdentityServer.

**Comment by leastprivilege** [comment]
when you type https://localhost in your browser you get an SSL warning - you need to fix that.

**Comment by Bala2Excel** [comment]
Thanks for your swift response, 

do you have any steps or can point me to any guide to fix that?

Currently, I have imported the certificate (which you have provided as part of source code) under Trusted Root Certfication &  Trusted People!

**Comment by leastprivilege** [comment]
That's unrelated. 

You need to configure your IIS / IIS Express for SSL. I don't have a doc right now - check Microsoft documentation.

**Comment by leastprivilege** [comment]
Alternatively you can set the validation moden to Local on the access token validation middleware - this will not use the validation endpoint. But this only shifts the problem that you need proper SSL to a later point in time.

**Comment by Bala2Excel** [comment]
Thanks for your inputs.
I used the below link, to set up Certificates using OpenSSL and I was able to invoke the service.

http://www.codeproject.com/Articles/683732/Thinktecture-Identity-Server-Configuration-Customi


Thanks a ton

**Comment by leastprivilege** [comment]
cool!
