### ISSUE TITLE
Don't show logout confirmation if valid id_token_hint is passed

### ISSUE THREAD

**Issue by leastprivilege** [thinktecture/Thinktecture.IdentityServer.v3#704]

**Comment by brockallen** [comment]
Done on dev. If SignOutMessage is passed, this will bypass logout prompt.

**Comment by mikeandersun** [comment]
I have the same issue.
@brockallen, Where is SignOutMessage? 
This is my code to signout:
 var properties = new AuthenticationProperties
            {
                RedirectUri = "http://localhost:2771/"
            };
             var athenticationManager = Request.GetOwinContext().Authentication;            
             athenticationManager.SignOut(properties);
            return Redirect(properties.RedirectUri);
------
but don't return to RedirectUri and I see a redirect to logout prompt page redirect in the chrome development tool(F12).
Thanks for a point to my mistake.

**Comment by brockallen** [comment]
You have to pass on when redirecting back to the OP (microsoft didn't implement this in their middleware) -- check the MVC samples for how to do it manually.

**Comment by mikeandersun** [comment]
I call the endpoint manually , but the same result.
   Request.GetOwinContext().Authentication.SignOut();
  return Redirect("https://myIdsrv/connect/endsession");

**Comment by brockallen** [comment]
Did you check the docs: https://identityserver.github.io/Documentation/docs/endpoints/endSession.html
