### ISSUE TITLE
Client Secret Encryption

### ISSUE THREAD

**Issue by jageall** [thinktecture/Thinktecture.IdentityServer.v3#705]
Client secrets should be encrypted in the data store as [per section 4.3.4](https://tools.ietf.org/html/rfc6819#page-24) of the threat model.

Additionally, I believe that the persistence layer should store at least an algorithm version and some form of key identifier so that the encryption can be changed if necessary over time.

**Comment by leastprivilege** [comment]
thanks! yes - that's indeed todo.

**Comment by leastprivilege** [comment]
Either we remove the feature of being able to sign id tokens with client secrets (which noone seems to use) and store them hashed - or we go through the pain of encryption.

**Comment by leastprivilege** [comment]
I think I will remove the client secret signing feature for now - then we can store the secrets hashed.

**Comment by jageall** [comment]
yeah good call, this issue can be pushed back to after RTM or when/if
people start needing it.

**Comment by leastprivilege** [comment]
OK - done on dev. Multiple new things

* new option on Client class to choose between secret protection: none and hashed
* a client can now have multiple secrets to make key rotation easier
* a client secret can now have an expiration date

give it a try and let us know if that works for you.

**Comment by jageall** [comment]
cool, I'll have a look tonight, sounds like I'll have a few changes to make :)
