### ISSUE TITLE
usernames with @ show as \x40

### ISSUE THREAD

**Issue by mnbob70** [thinktecture/Thinktecture.IdentityServer.v3#708]
![image](https://cloud.githubusercontent.com/assets/9770874/5603429/3e218b74-934a-11e4-82e1-e270606954eb.png)

**Comment by leastprivilege** [comment]
Is that dev or master?

**Comment by mnbob70** [comment]
From nuget package.

**Comment by leastprivilege** [comment]
This is fixed on dev build (on myget)
