### ISSUE TITLE
"Getting started" page doesn't mention getting idsrv3test.pfx or adding it to project

### ISSUE THREAD

**Issue by RPrimrose** [thinktecture/Thinktecture.IdentityServer.v3#711]
On the "Getting started" wiki page, the "Adding Startup" section creates a certificate using the file "idsrv3test.pfx" but there isn't anything on the page mentioning where to obtain the file from or that it needs added to your project and to have "Copy to Output Directory" enabled.

It's easy enough to work out from the code samples but should be in the tutorial as well.

**Comment by leastprivilege** [comment]
thanks - moved to docs repo
