### ISSUE TITLE
login button is disabled, if the login text fields are autofilled by chrome

### ISSUE THREAD

**Issue by jaundice** [thinktecture/Thinktecture.IdentityServer.v3#713]
repro steps:
run mvc authentication demo in chrome
go to login page
login as bob/secret
when chrome asks, save login details
logout
go to login page
username and password fields are both filled but the login button is disabled. Clicking on it will enable it and a second click will submit

**Comment by brockallen** [comment]
Seems to be a common issue with angular:

https://stackoverflow.com/questions/14965968/angularjs-browser-autofill-workaround-by-using-a-directive

**Comment by brockallen** [comment]
Ok, this seems to be a chrome bug and I don't have time to work on it now. If it's sufficiently annoying, please send a PR. Thx.
