### ISSUE TITLE
When using Email as Username email gets encoded

### ISSUE THREAD

**Issue by jerackista** [thinktecture/Thinktecture.IdentityServer.v3#714]
By entering wrong credentials at Login UserName gets encoded (name@domain.com becomes name\x40domain.com)

Thinktecture.IdentityServer.Core.ViewModels.LoginViewModel 

        public string Username
        {
            get
            {
                return Microsoft.Security.Application.Encoder.JavaScriptEncode(_Username, false);
            }
            set
            {
                _Username = value;
            }
        }

**Comment by leastprivilege** [comment]
have you tested that on the dev build?

**Comment by jerackista** [comment]
I was on master. Sorry. On dev works OK!

**Comment by leastprivilege** [comment]
no prob
