### ISSUE TITLE
Problems overriding CSS for embedded Views

### ISSUE THREAD

**Issue by appetere** [thinktecture/Thinktecture.IdentityServer.v3#715]
I have been trying to add a stylesheet to override the embedded views styling (based on the previous version's [wiki notes](https://github.com/thinktecture/Thinktecture.IdentityServer.v3/wiki/Customizing-Views), but with IdentityServer3 Beta4-1). 

I've hit two problems:

**Stylesheet path resolution with virtual directories**

I've added a stylesheet in "/Content/site.css" in my IdentityServer3 host project.  Then configured `Startup` to serve files from that directory:

    app.UseStaticFiles("/Content");

This works fine when I type in the URL directly, so with a virtual directory `IdentityServer3` I can make a request `https://localhost/IdentityServer3/content/site.css` and the file is returned.

I then configured `IdentityServerServiceFactory` as follows:

    var defaultViewServiceConfiguration = new DefaultViewServiceConfiguration();
    defaultViewServiceConfiguration.Stylesheets.Add("~/Content/site.css"); 
    serviceFactory.Register(
      new Registration<DefaultViewServiceConfiguration>(defaultViewServiceConfiguration));

This resolves the stylesheet path as `https://localhost/IdentityServer3/core/Content/site.css`.  This has taken `/core` as the base-path, so the file site.css is no longer found.

I also tried setting 

    defaultViewServiceConfiguration.Stylesheets.Add("/Content/site.css"); 

but this then misses out the virtual directory `IdentityServer3`, resulting in a generated path `https://localhost/Content/site.css` which is also not found.

My ideal behaviour would be for `~/xyz` to resolve from the root directory for the website, rather than the `/core` path that IdentityServer3 is using.

As it stands, I can't see how I can use a virtual directory, except by hard-coding the path.  I don't want to do that, as the virtual directory is only being used in development and will not used in production.

**Instantiate DefaultViewServiceConfiguration.Stylesheets with a collection that maintains order**

To override a couple of elements in the default styling of the views I've just added my stylesheet to the collection which contains the default styling (see above).

But the default implementation uses a HashSet for the stylesheets:

    public DefaultViewServiceConfiguration()
    {
        // adding default CSS here so hosting application can choose to remove it
        Stylesheets = new HashSet<string>
        {
             "~/assets/styles.min.css"
         };

Therefore the order of the stylesheets is not guaranteed to be the order they were added, which is important to produce the expected result.

So instead of HashSet, could you use List<string> so the order is preserved?

I can work around this by setting the Stylesheets property to a new List<string> myself, but then would have to include the `~/assets/styles.min.css` string, which is an IdentityServer3 implementation detail that could change.

**Comment by brockallen** [comment]
For the first issue, I don't have a solution. We support ~/ to be OWIN relative (not IIS).
For the second issue -- I agree. Order is important and I'll change the Hashset to a List.

**Comment by brockallen** [comment]
Ok, done on dev.

**Comment by appetere** [comment]
@brockallen Thanks for updating the HashSet so quickly.

Understand about the ~/ being relative to the current context.  As a workaround, I've made my stylesheet use a URL with `core` in the path, `https://localhost/IdentityServer3/core/content/site.css` by setting:

    defaultViewServiceConfiguration.Stylesheets.Add("~/Content/site.css");

Then added the following into my `Startup` code, just before the IdentityServer3 configuration is done:

    app.UseStaticFiles(new StaticFileOptions
    {
        RequestPath = new PathString("/core/content"),
        FileSystem = new PhysicalFileSystem("Content")
    });
    app.Map("/core", coreApp =>
       { ...

This then seems to serve up the stylesheet correctly.  And I just have to hope you don't add a `core/Content` directory of your own in the future!

**Comment by brockallen** [comment]
Yep, that works.

**Comment by apylypchuk** [comment]
This worked for me:
```
string absolute = VirtualPathUtility.ToAbsolute("~/Content/css/main.css");
viewOptions.Stylesheets.Add(absolute);
```
