### ISSUE TITLE
Question: Refreshing access tokens when using implicit flow

### ISSUE THREAD

**Issue by johnkors** [thinktecture/Thinktecture.IdentityServer.v3#719]
Hi,

We've set up a RP with a client assigned for implicit flow, and are looking at refreshing access tokens before exipiry. As refresh tokens [aren't supported](https://github.com/thinktecture/Thinktecture.IdentityServer.v3/wiki/Token-Endpoint) for implicit flow we are unsure of what would be the best way to get new access tokens when the RP is using the implicit flow.

Is there any other way than having to create another Client (in the Client Store) with a flow set to Client Credentials for the same RP and use this?

Or do we have to switch to code flow + refresh tokens?

**Comment by leastprivilege** [comment]
depends on the type of RP - JS cliens can automatically refresh tokens as long as the logon session is valid at the OP (see the JsOAuth sample). Server side applications should use code flow and refresh tokens.

**Comment by johnkors** [comment]
Thanks for the swift reply!  Just wondering about your comment how the js sample automatically may refresh access tokens. How is it doing this - by polling the authorize endpoint? 

It's [this js sample](https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/blob/dev/source/Clients/JavaScriptImplicitClient/index.html) you are talking about, right?

We'll have both kind of clients, so better learn all options. :)

**Comment by leastprivilege** [comment]
no this one
https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/tree/dev/source/OAuthJS

**Comment by xmichaelx** [comment]
https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/tree/dev/source/OAuthJS <- this link is dead

**Comment by Ciantic** [comment]
With JS apps one can refresh the access token by issuing a new authorization in hidden iframe when the old one is expired. 

There is also a extra query argument that is useful for it, add `&prompt=none` which also required that you have `&id_token_hint=...` to the authorization request and the server should redirect to redirecturi as soon as possible, without getting stuck login form if the user is not logged in.

More about prompt=none in the [OpenId Authorization Endpoint spec.](http://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint)
