### ISSUE TITLE
PostLogoutRedirectUri not shown for Logout from consent screen

### ISSUE THREAD

**Issue by appetere** [thinktecture/Thinktecture.IdentityServer.v3#720]
Using the sample "JavaScript Implicit Client" to illustrate:

- Start the login process and get to the consent screen
- Expand the drop-down on the navbar and click Logout
- The "You are now logged out" page is displayed, but the post-logout redirect (defined in Clients in the Host project) is not displayed.

Extract from Clients:

>new Client
>{
>      ClientName = "Implicit Client Demo",
>      ClientId = "implicitclient",        
>      PostLogoutRedirectUris = new List<string>
>      {
>          "http://localhost:23453/index.html",
>        },

Seems to be something like the call to the EndSession endpoint is missing some parameters?

**Comment by leastprivilege** [comment]
Well . you need to pass the logout url and the id token hint. check the spec ;)

**Comment by appetere** [comment]
But the Logout link on the consent page is generated by the core Thinktecture code, so I'm not clear how I can add the id token hint myself?

**Comment by leastprivilege** [comment]
oh I see - yea I think that's a dead end. @brockallen right?

**Comment by brockallen** [comment]
Yes, right now that just logs you out of IdSvr -- it doesn't know about any clients. If it's something you have an opinion on, open a new issue for a feature request.
