### ISSUE TITLE
Where is the stock MembershipReboot UserService implementation?

### ISSUE THREAD

**Issue by kalanbates** [thinktecture/Thinktecture.IdentityServer.v3#722]
I understand that this is Beta; that's why I figured it'd be simpler to ask than scour the code base looking for something that I don't know I will find.

Core.Configuration.IdentityServerServiceFactory's comments for the UserService property (along with the videos based on Preview 1) indicate that there is a standard implementation of the MembershipReboot UserService.

Code comment (line 90)
```
Gets or sets the user service. The user service implements user authentication against the local user store as well as association of external users. There are standard implementations for in-memory, MembershipReboot and ASP.NET Identity
```

However, the only implementation of IUserService that CodeLens retrieves is the InMemoryUserService.  

What happened to the MembershipReboot UserService? 
Is it still in the solution?
Where should I be looking for it?

**Comment by brockallen** [comment]
Here: https://github.com/thinktecture/Thinktecture.IdentityServer.v3.MembershipReboot/

**Comment by kalanbates** [comment]
Awesome!   I guess my confusion stemmed from the Preview 1 "IdentityServer.v3 extensibility support" video that shows the MembershipReboot and ASP.NET Identity UserServices as projects in the IdentityServer "UserServices" solution folder.  After finding the InMemoryUserService implementation, I had somewhat assumed that the implementations would be part of IdentityServer.Core.Services.

Thank you for the quick answer.

**Comment by binarymist** [comment]
I was wondering what that project was for:s
