### ISSUE TITLE
How can we use Bearer Token in HTML Page

### ISSUE THREAD

**Issue by skatukojwala** [thinktecture/Thinktecture.IdentityServer.v3#723]
We are using OAuth for Authentication. I know we can use the Access Token as a Bearer Token while accessing RESTful API calls. How are going to use these bearer tokens with HTML pages, we have a scenario where once the user is Authenticated, it loads HTML page which has JavaScript includes.  we these HTML pages to if the HTML page is authorized to download the JavaScript.

**Comment by brockallen** [comment]
You want to use the bearer token to authenticate the download of JavaScript? Or you want to use the bearer token from JavaScript to call an API?

**Comment by skatukojwala** [comment]
How do I use bearer token in HTML to authorize download of JavaScript.   In HTML file we have includes to JavaScript files which needs authorization to download.

**Comment by brockallen** [comment]
I'd not use the token and instead rely upon a cookie from the web server.

**Comment by skatukojwala** [comment]
One of the main reason we moved to OAuth is to use Token based authentication and move away from Cookie based authentication. I see that this bearer token simplifies authorization for RESTFulAPI calls, but it looks like we still need to rely on Cookie for Authentication.   I which we could use same mechanism for any HTML stuff, I agree that this was developed to work with Cookies.  

Other approach I am thinking of using is to write controller that generated HTML based on Authorization.

**Comment by brockallen** [comment]
Cookie authentication is just fine for HTML based apps. Token authentication is fine for programmatic API calls. What's appealing about them both is that the value is passed via headers.

Using a token for a HTML include (like an img or a script) is more complicated, since the token would have to be used via the query string or in the URL somehow. This is what complicates things.

**Comment by skatukojwala** [comment]
Thank you for quickly responding to my questions!
This was very helpful and appreciate your help.
