### ISSUE TITLE
resource scopes to users

### ISSUE THREAD

**Issue by StevenReachSoftware** [thinktecture/Thinktecture.IdentityServer.v3#724]
Hi,

I'm convinced I've seen an answer to this before, but can not find it for the life of me.  Is there a way to associate users to scopes?  For instance in my application users are granted access to certain resource scopes, then inside that they have additional rights via roles.  I think this approach is a little bit reverse from the typical OAuth use case where it's the user granting access to the client to access a resource but it makes sense in our situation.

I gather I can accommodate this scenario by using a custom IClaimsProvider, but is there a 'built-in' way of doing it?

If not; I'm thinking I would store something like this in the user's claims

    new Claim(Constants.ClaimTypes.Scope, "myscope")

then check for those in the GetAccessTokenClaimsAsync and GetIdentityTokenClaimsAsync methods.

Could you suggest a better integration point for such a check?

**Comment by leastprivilege** [comment]
for an explanation of the terms - see here: https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/overview/terminology.html

**Comment by stevenfirstrowinc** [comment]
Ok, I've read that. I understand that a Client requests a Scope and Users can grant that Client access to the Scope.  But I'm not sure how it answers my question, probably because my question wasn't clear.  

In my situation the user doesn't always have access to the resource scope.  How can I reflect that when a user tries to authenticate and is requesting a scope they don't have access to?  Do I just fail their authentication check?

**Comment by StevenReachSoftware** [comment]
Ok, I've read that. I understand that a Client requests a Scope and Users can grant that Client access to the Scope.  But I'm not sure how it answers my question, probably because my question wasn't clear.

**Comment by brockallen** [comment]
Are you trying to restrict which users can access which clients? If so, IdentityServer allows for custom validation of the requests via the ICustomRequestValidator interface. You can implement this and return an error to prevent a user from getting a token for a client.

**Comment by StevenReachSoftware** [comment]
That's it!  sorry I knew I wasn't saying it right.  Is there a sample of this or am I right in my above line of thinking?  In other words store something like this on the user

    new Claim(Constants.ClaimTypes.Scope, "myscope")

and check that as part of ICustomRequestValidator

**Comment by leastprivilege** [comment]
I wouldn't re-purpose the scope claim. Do your checks in the validator - no need harm a scope ;)

**Comment by StevenReachSoftware** [comment]
I can work with that!  I just need to store something with the user, you are saying just use a custom claim?

**Comment by brockallen** [comment]
You have total freedom to build whatever logic you want to determine if the user is allowed or not -- could could have a separate table in some Db that has the rules. It's all custom.

**Comment by StevenReachSoftware** [comment]
got it.  Thanks very much for your help and the product.  We are making good use of it.
