### ISSUE TITLE
Why does ValidateCustomGrantRequestAsync return Invalid if no Principal?

### ISSUE THREAD

**Issue by appetere** [thinktecture/Thinktecture.IdentityServer.v3#726]
`Thinktecture.IdentityServer.Core.Validation.ValidateCustomGrantRequestAsync` always returns an Invalid result if `result.Principal` is null:

            if (result.Principal == null)
            {
                if (result.ErrorMessage.IsPresent())
                {
                    LogError("Invalid custom grant: " + result.ErrorMessage);
                    return Invalid(result.ErrorMessage);
                }

                Logger.Error("Invalid grant.");
                return Invalid(Constants.TokenErrors.InvalidGrant);
            }

            _validatedRequest.Subject = result.Principal;

Is this correct?  I would have thought it was fine to return a null Principal for some custom grants (and the downstream code (eg `DefaultClaimsProvider.GetAccessTokenClaimsAsync`) already allows null subjects for other standard grant-types:

            // a user is involved
            if (subject != null)
            {
                outputClaims.AddRange(GetStandardSubjectClaims(subject));
                outputClaims.AddRange(GetOptionalClaims(subject));
            [...]

**Comment by leastprivilege** [comment]
So right now - null principals mean that no human is involved (and thus only really allowed for client credentials flow).

Are you saying you need the feature that you want to use a custom grant without a user context? That's fine - just want to understand the scenario.

**Comment by appetere** [comment]
I have created a modified Client Credentials flow, but in fact my modification is to add a subject to the  access token.  So I do create a Principal and the current code does work for me.  I just thought the null Principal check seemed an unnecessary restriction for other possible custom flows.

After implementing a CustomGrantValidator I do have an enhancement suggestion though:-

- I am using a custom flow based on OAuth2 Client Credentials.
- As per the OAuth2 spec (4.5. Extension Grants), I set the "grant-type" to my custom flow name

I would now like to check that my `Client` is allowed to use that grant-type in a similar way to `Client.ScopeRestrictions` restricts scopes.

While I have only one custom grant-type a check is not actually needed, since the CustomGrantValidator only supports one grant type.

But if more than one custom grant-type is implemented, then you would want to check that the Client is allowed to use that grant-type.  So something like a `Client.CustomGrantRestrictions` would be needed.

Neither of the above points are stopping me using my single custom-grant-type.  So they are just future-proofing suggestions which you may want to ignore for now!

**Comment by leastprivilege** [comment]
OK - CustomGrantType restrictions added - as well as the ability to return null principals from the validator. Both on dev - will go live with RC on monday.
