### ISSUE TITLE
Failed login breaks username as email

### ISSUE THREAD

**Issue by danda1man** [thinktecture/Thinktecture.IdentityServer.v3#727]
When login fails for username/password login and the username is an email address, the '@' symbol is encoded to '\x40'.  Best scenario would be to allow the @ symbol to remain, better than current would be to clear the field entirely instead of leaving bad value in place.
![received_10205786460568563](https://cloud.githubusercontent.com/assets/852995/5648004/84170952-9650-11e4-9400-2f0b1c576b50.jpeg)

**Comment by brockallen** [comment]
This is fixed on dev.
