### ISSUE TITLE
IdentityServerOptions.RequireSsl seems to break :/

### ISSUE THREAD

**Issue by ciaranj** [thinktecture/Thinktecture.IdentityServer.v3#728]
If requireSSl is set to true but a request to '.well-known/openid-configuration' is made through a non SSL connnection, rather than get the expected 403 we get an error:

    Server Error in '/Host' Application.
    
    Value cannot be null.
    Parameter name: context
    
    Description: An unhandled exception occurred during the execution of the current web request.     Please review the stack trace for more information about the error and where it originated in the     code. 
    
    Exception Details: System.ArgumentNullException: Value cannot be null.
    Parameter name: context
    
    Source Error: 
    
    
    Line 125:        {
    Line 126:            var scope = env.GetLifetimeScope();
    Line 127:            var instance = (T)scope.ResolveOptional(typeof(T));
    Line 128:            return instance;
    Line 129:        }
    
    Source File:     p:\development\Thinktecture.IdentityServer.v3\source\Core\Extensions\OwinExtensions.cs    Line:     127 
    
    Stack Trace: 
    
    
    [ArgumentNullException: Value cannot be null.
    Parameter name: context]
       Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service     service, IEnumerable`1 parameters) +246
       Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.ResolveDependency(IDictionary`2     env) in     p:\development\Thinktecture.IdentityServer.v3\source\Core\Extensions\OwinExtensions.cs:127
       Thinktecture.IdentityServer.Core.Configuration.Hosting.<Invoke>d__0.MoveNext() in     p:\development\Thinktecture.IdentityServer.v3\source\Core\Configuration\Hosting\RequireSslMiddle    ware.cs:42
       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
           System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) +84
       Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +777
       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
           System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) +84
       Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +291
       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
           System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) +84
       Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +293
       System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
           Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsync    Result ar) +208
       System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()     +434
       System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&     completedSynchronously) +288
    
'T' for my situation is ILocalizationService if that helps.

Noted when I updated my code to Beta4-1 (one of my integration tests around forcing SSL started to fail) and re-tested against the current HEAD of the dev branch commit:d5c2212 still seeing the failure.

**Comment by brockallen** [comment]
fixed on dev. thx.
