### ISSUE TITLE
New Client Claims functionality strips the claim value type

### ISSUE THREAD

**Issue by ciaranj** [thinktecture/Thinktecture.IdentityServer.v3#730]
Not sure if this is intentional, but the new client claims support (thank you!) seems to strip out the claim value type, so clients can only return claims of type 'string'.  Is this deliberate ? (Line 145 of DefaultClaimsProvider is only using the 2 argument constructor when it does the rename)

**Comment by leastprivilege** [comment]
Do you need that feature? This is not intentional - just didn't think abou it.

**Comment by ciaranj** [comment]
Hmm I guess technically not, I can pretty much always infer it from the claim name.  I just kinda 'assumed' it would be needed, and when I ported over my tests from my previous custom client-claims implementation they started failing!

**Comment by leastprivilege** [comment]
I'll look into it.

**Comment by leastprivilege** [comment]
fixed on dev

**Comment by leastprivilege** [comment]
thanks

**Comment by ciaranj** [comment]
Thank you :)
