### ISSUE TITLE
Multiple Relaying Party Apps Signout issue

### ISSUE THREAD

**Issue by tsladev001** [thinktecture/Thinktecture.IdentityServer.v3#736]
With multiple RP Apps, let say App1 is logged in, open App2 in another tab. App2 is does not required login as in the same browser. Now if I logout from App1 first, then logout from App2 second. I am seeing login screen for both App1 and App2. Now if I try to login to App1, it throws exception. For App1 I can see there is ?signin=xxxxxxxxxx quesyString and also there is same kind of queryString with App2. What I observed is that there is cookie created like .SignInMessage.xxxxxxxxxxxxxxxxx, so it is not present for App1, while App2it is present. I think server is over-writting .SignInMessage cookie, if we do signout from multipe Apps in the same browser. Is there is any solution or work around for this issue. As for Signout, I always see multiple .SignOutMessage cookies, why not multiple .SignInMessage cookies?

**Comment by brockallen** [comment]
Fixed on dev. Thx.
