### ISSUE TITLE
OwinEnvironmentService Environment not persisting data within same userSession

### ISSUE THREAD

**Issue by tsladev001** [thinktecture/Thinktecture.IdentityServer.v3#737]
I have added the following OwinEnvironmentService class: public class OwinEnvironmentService
{
readonly IOwinContext _context;
public OwinEnvironmentService(IOwinContext context)
{
_context = context;
}
public IDictionary<string, object> Environment
{
get
{
return _context.Environment;
}
}
Register it in AutoFacConfig.cs as: builder.RegisterType<OwinEnvironmentService>().AsSelf();
So in AuthenticationController I am setting values like: owinEnvironmentService.Environment.Add("UserName", model.Username);, here it adds successfully
now when I use it in DefaultClaimsProvider.cs(method: GetIdentityTokenClaimsAsync) as owinEnvironmentService.Environment["UserName"], it does not have UserName key. Any idea what I might be missing?

**Comment by brockallen** [comment]
I hope you understand we can't help out when the source code is being changed. We can only support the code we've written and tested and the extensibility points we've designed. Sorry.
