### ISSUE TITLE
OwinContext RequestId is all zeros

### ISSUE THREAD

**Issue by tsladev001** [thinktecture/Thinktecture.IdentityServer.v3#738]
Hi, Is there is any value in the default OwinContext environment dictionary that is unique per request?
I am seeing one key value: owin.RequestId in the Owin Environment dictionary, but it is all zeros("00000000-0000-0000-0000-000000000000"), any idea why it is zeros or where it can be set?

**Comment by brockallen** [comment]
There's an extension method on the OWIN environment called `GetRequestId` (on the dev branch).

**Comment by dannyarica** [comment]
Did you fix this? I am getting the same error in a deployed env. Locally I can see a proper GUID for each new request.
Please help me...

**Comment by brockallen** [comment]
It will only work if you're calling it in the same pipeline as IdentityServer

**Comment by dannyarica** [comment]
But, how do you explain when I run locally I am able to see a valid requestId, then When I proceed to deploy, logs are returning 00000-0000
I suspect maybe some configuration is skiped in deploy env?

**Comment by brockallen** [comment]
not sure
