### ISSUE TITLE
Question regarding single-sign on

### ISSUE THREAD

**Issue by danielbsig** [thinktecture/Thinktecture.IdentityServer.v3#739]
I have a general question regarding IdentityServer (or perhaps OpenID Connect in general) and Single Sign-on.

Assume I've got a Single-Page Application which talks to my REST Backend (written in C# Web API). A user has already signed in to the application using IdentityServer. Now the user wants to use the REST API from another application - say, Excel, in a VBA script (s)he is writing.

Is it possible to configure the system such that the user is still authenticated, i.e. requests for the Web API coming from a script in Excel will include the necessary token by default?

Best regards,
Daníel

**Comment by brockallen** [comment]
Excel would have to know how to request the token, and then use it.

**Comment by leastprivilege** [comment]
if the SPA and Excel use the same browser to request the token - you can potentially share the authentication cookie.

**Comment by danielbsig** [comment]
Ah ok, so if the Excel script code would use for instance the IE COM object, then it should be possible. Thanks!

**Comment by leastprivilege** [comment]
Maybe - and only for one of the flows that uses a browser (e.g. implicit)
