### ISSUE TITLE
Error during Publish

### ISSUE THREAD

**Issue by fatagun** [thinktecture/Thinktecture.IdentityServer.v3#740]
Hello, 
Upon publishing the project I am getting :

Error	1	The target "GatherAllFilesToPublish" does not exist in the project.	C:\Users\Me\Desktop\Thinktecture.IdentityServer.v3-master\source\Host\Host.csproj	0	0	Host

How I can i fix this?

Thanks.

**Comment by leastprivilege** [comment]
don't know - we don't use that project for publishing.

**Comment by fatagun** [comment]
well what do you use for publishing?

**Comment by leastprivilege** [comment]
Some host that is using the nugets

**Comment by leastprivilege** [comment]
i mean that said - yes there is an error ;) I just never bothered to fix it. Google returns plenty of results - send us a PR. thanks ;)

**Comment by fatagun** [comment]
thanks:)

**Comment by paul3291** [comment]
This one fixed it for me, just grabbed the property group from an existing 2013 web application and pasted it in. The version is 12 instead of 10 from memory..

http://forums.asp.net/t/1838524.aspx?The+target+GatherAllFilesToPublish+does+not+exist

<PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
 </PropertyGroup>

**Comment by aasf86** [comment]
solved, is simple, create new project web, copy and paste that code Startup.cs and import dependences. ready it's funny
