### ISSUE TITLE
Android native app client OAuth2

### ISSUE THREAD

**Issue by dontbesorry80** [thinktecture/Thinktecture.IdentityServer.v3#742]
We are writing an android app which will communicate with Asp.Net Web API 2. I have secured the WebAPI to use bearer tokens. I have this working nicely from .Net clients. I see from an old article of yours you illustrated how to use resource owner password flow. I'm trying to set this up using a native android app. Do you need a redirect uri? I'm not sure what I would provide if this is required?

**Comment by leastprivilege** [comment]
RO flow does not need a redirect URI.

**Comment by dontbesorry80** [comment]
Great It's all working now! Thanks.
