### ISSUE TITLE
Getting started. ResponseType = "id_token"

### ISSUE THREAD

**Issue by vincenzo-antolini-os** [thinktecture/Thinktecture.IdentityServer.v3#744]
Hi,
what is the default value for ResponseType property?

I found that if I not specify a ResponseType, the Getting Started example works correctly.
On the opposite, if specified as `ResponseType = "id_token"` I get an error message:
_The client application tried to access a resource it does not have access to._

After some debug I found that if `ResponseType = "id_token"` is specified ids does not retrieve profile data.
I used Flows.Hybrid.

Is this correct?

The relation between Scopes, Profiles and Clients is my big challenge :)

Thanks in advance
V

**Comment by leastprivilege** [comment]
There is no default value - it depends what you want ;)

maybe check the docs first

https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/overview/terminology.html

**Comment by vincenzo-antolini-os** [comment]
Got it!
_Clients request token at the OP. Depending on the scopes requested, the OP will return an identity token, an access token or both._

I'll have to try some different scenarios...
