### ISSUE TITLE
Registration<T> vs RegistrationType<T>

### ISSUE THREAD

**Issue by vincenzo-antolini-os** [thinktecture/Thinktecture.IdentityServer.v3#745]
The documentation
http://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/advanced/customServices.html
At the end shows this code:

```
var factory = new IdentityServerServiceFactory();
factory.UserService = Registration.RegisterType<IUserService>(typeof(MyCustomUserService));
```

I get a compilation error. 'RegisterType' is not defined.
I have changed code to

```
var factory = new IdentityServerServiceFactory();
factory.UserService = new Registration<IUserService>(typeof(MyCustomUserService));
```
and it works. Honestly I'm not sure about it. Is it ok?

Thanks in advance
V

**Comment by leastprivilege** [comment]
that's correct.

The docs are out of sync right now.
