### ISSUE TITLE
CookieAuthentication - get new token via Ajax

### ISSUE THREAD

**Issue by totoo** [thinktecture/Thinktecture.IdentityServer.v3#746]
Hi, 

For my Single Page Application I want to 'refresh' my token via Ajax call from my MVC View. 

Example: As a user I got a token for 1h, I have SPA application with ajax calls, and standard cookie authentication in MVC site. 

I can't get new token via iframe, because there is X-FRAME-OPTIONS.

What is the best way to get new token without refresh web page in the browser?

**Comment by brockallen** [comment]
Look at the OAuth2 JS sample -- it uses the TokenManager JS helper library for such things: https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/tree/master/source/OAuthJS
