### ISSUE TITLE
Get username during SignOutAsync(ClaimsPrincipal subject)

### ISSUE THREAD

**Issue by imperugo** [thinktecture/Thinktecture.IdentityServer.v3#749]
Hi, 
I wanna add some logic after logout, but it seems there is no way to get the username for the logged user into SignOutAsync(ClaimsPrincipal subject) (```IUserService```).
Probably the method is called after the login.

in fact this

```csharp 
subject.GetSubjectId()
```

get me this

```
System.InvalidOperationException: sub claim is missing
   at Thinktecture.IdentityServer.Core.Extensions.PrincipalExtensions.GetSubjectId(IIdentity identity) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Extensions\PrincipalExtensions.cs:line 60
```

Is there a way to this?

**Comment by brockallen** [comment]
Are you on the RC release? It should be working there.

**Comment by imperugo** [comment]
Nope, I wasn't.
Just updated the package and it works.

Thanks
