### ISSUE TITLE
Client Ip Address int IUserService

### ISSUE THREAD

**Issue by imperugo** [thinktecture/Thinktecture.IdentityServer.v3#754]
Hi, 
into my IUserService I need to check the IP address of the user and do some stuff (i.e: I can allow only users who come from a specific ip range, otherwise no login with a specific message).

What is the best way to get the clientIP into IUserService (AuthenticateLocalAsync in my case)?

Thanks

**Comment by leastprivilege** [comment]
inject OwinEnvironmentService

**Comment by imperugo** [comment]
Hi @leastprivilege 
but what about singleton lifecycle? IUserService is a singleton right?

factory.UserService = new Registration<IUserService>(userService);

If I inject OwinEnvironmentService into it will be always the same for all the requests, with obvious problems.

Am I wrong?

**Comment by leastprivilege** [comment]
I wouldn't do the user service as a singleton.

**Comment by mdennis10** [comment]
I'm not seeing any method to get the remote client IP from the OwinEnvironmentService?
