### ISSUE TITLE
Architecture Advise For Multiple User Types + Shared Apis 

### ISSUE THREAD

**Issue by mickdelaney** [thinktecture/Thinktecture.IdentityServer.v3#757]
I have a question about how to tackle my current situation.  

My system has 3 different types of User:
- Employers
- Admin
- Contractors

- Each user is currently stored in a different database. 

- They have rules around where they can login from, 
e.g. 
Admin can never use social, and has no registration functionality, invite only
Contractors can use social & registration
Employers will have enterprise SSO & invite based sign up. 

- They access both SHARED Apis (available to all) AND PER USER Apis (only available to each user type). 
e.g. 
Each has they're own api:
Employer.Api, Admin.Api, Contractors.Api, 

Apis Used By All:
- Common.Api
- Companies.Api
- Data.Api

- Shared api's would need to access an authority, e.g. idsrv/core 
- They'd probably have one or more scopes

- How can I allow a single instance of idsrv support 3 different authentication scenarios
whilst allowing the shared api's to support ALL 3 users (provided they have the scope) ?

Considered: 

Multiple Instances:
-------------------------------------------------------
- Mapping Multiple Instances Of Idsrv on the one web app, and then pointing each client to 
the relevant one. 
- A Custom UserService For Each One 
- Have them share the same scopes & certificates etc. 
- Having them all use the same IssuerUri (is that possible) 

- Have maybe a 'core' instance also that the shared APIs would use i.e. app.UseIdentityServerBearerTokenAuthentication(options);

- But i'm assuming this will break down ???

Migrating To A Single Database For All Users:
-------------------------------------------------------
- This would be a much bigger undertaking 
- Not Sure I want them in the same DB. 
- There's different security & SLA requirements for each one

Ideally the simplest thing that works to get me over the line would be best :-) 

Thanks In Advance.

**Comment by leastprivilege** [comment]
nice try ;) you need proper consulting for that...:)

**Comment by mickdelaney** [comment]
LOL ...
