### ISSUE TITLE
Missing signin cookie

### ISSUE THREAD

**Issue by johnkors** [thinktecture/Thinktecture.IdentityServer.v3#762]
Hi guys,

we recently upgraded to RC, and we started seeing cases of a missing SignInMessage.GUID cookie and the error ```There is an error determining which application you are signing into. Return to the application and try again.```. Logs say "Missing signin cookie".. Is this a known issue? The cookie gets set if I hit back and retry the login from the RP however.

I'm able to reproduce it by using another browser I never use (read as IE). Same experience for new users that haven't used our environment yet. 

Related to other issues and clearing of cookies?

**Comment by brockallen** [comment]
Do you have exact repro steps?

**Comment by johnkors** [comment]
Yeah sure, all I do is
1. Open a new IE instance and go to RP.
2. Click login at RP (code flow using the MS OpenId Connect MW)
3. Get redirected to the login view with an immediate error msg because of the missing cookie.

As mentioned, if I go back within the same IE session to the RP and start over, the login view does not show an error (the cookie exists).

**Comment by leastprivilege** [comment]
I can't repro that - could you provide a network trace?

**Comment by johnkors** [comment]
sure, on what format?

**Comment by johnkors** [comment]
HAR file: https://www.dropbox.com/s/r2uopj9058qh6ne/network.har?dl=0

**Comment by leastprivilege** [comment]
Could you try that here:
http://coding.abel.nu/2014/11/catching-the-system-webowin-cookie-monster/

**Comment by johnkors** [comment]
Will give it a go. Will anywhere in the pipeline work for Kentor? We have the following MWs in the same app.

```
        app.UseKentorOwinCookieSaver();
        app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                CookieName = "idsrv"
            });
            
       app.StartupIdentityServer();
       app.UseWebApi(..)

```

**Comment by johnkors** [comment]
hm, that had some interesting side effects... no error, but also no views rendered.

**Comment by leastprivilege** [comment]
why do you need all that stuff in your startup?

look here e.g. for a clean web host: https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/tree/master/source/WebHost%20(minimal)

**Comment by johnkors** [comment]
We're currently hosting a user registration app, and the idsrv admin views in the same app as idsrv itself, so a bit more than just idsrv running. Yep, aware of the hosting options. If the issues persist we'll have to extract idsrv to a clean host.. Just a buzz kill to get these errors now in RC, since they just ocurred with the RC. The beta packages were running fine..  :/

**Comment by brockallen** [comment]
Hmm, yea -- put IdentityServer inside its own `Map`.

**Comment by johnkors** [comment]
Yep, can do. We had isrv at the site root. Will put it back at /core

**Comment by johnkors** [comment]
Phew. That worked.. I also removed the Kentor MW to test it without it. Keeping idsrv at a seperate vpath did the trick. Will keep it that way :)

Thanks again for taking the time to investigate, both of you. :+1:

**Comment by brockallen** [comment]
np
