### ISSUE TITLE
Get Access to UserManager inside my own controller

### ISSUE THREAD

**Issue by mstrong64** [thinktecture/Thinktecture.IdentityServer.v3#764]
I'm using IdSrv with Asp.Net.Identity and need to get access to the UserManager of the IUserService inside a controller. I need to be able to call UserManager.FindByEmailAsync() and UserManager.CreateAsync(). Any suggestions?

**Comment by brockallen** [comment]
Configure it in the Di system. https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/advanced/di.html

**Comment by mstrong64** [comment]
Thanks @brockallen. I am actually already using DI as per the example:

`factory.UserService = new Registration<IUserService>(resolver => AspNetIdentityUserServiceFactory.Factory());`

The factory returns my custom IUserService that has the `UserManager` as `public`. Inside the controller I use the resolver to get the service:

`var userSvc = Request.GetOwinContext().Environment.ResolveDependency<IUserService>();`

However, this returns `ExternalClaimsFilterUserService` not `IUserService`. If I inspect `userSvc` I can see my class in the `inner` property, under which I can see `UserManager` but of course that's not available to my code. Looking into the IdSrv code I see this in `AutofacConfig`:

`builder.RegisterDecorator<IUserService, ExternalClaimsFilterUserService>(fact.UserService);`

There is no other reference to `IUserService` in that class. Has this got anything to do with my problem? Am I trying to reference the service correctly? If it worked as I was expecting, would `UserManager` actually be 'public`?

Thanks for your help.

**Comment by mstrong64** [comment]
I don't know why using the factory was causing a problem, but implementing the DI like this fixed the problem:

`factory.Register(new Registration<MyUserManager>(typeof(MyUserManager)));`
`factory.UserService = new Registration<IUserService>(typeof(MyUserService));`

**Comment by brockallen** [comment]
Yea, the DI system was updated slightly -- so the last approach you show is what's best/recommended.

**Comment by CiprianPorumbescu** [comment]
Sorry to open this discussion after that much time but I'm too trying to access the UserService from the Controller and I fail in doing this. Like mstrong64 I tried
```
var userSvc = Request.GetOwinContext().Environment.ResolveDependency<IUserService>();
```
The problem is that ResolveDependency extension is internal. What am I missing?
Thanks

**Comment by brockallen** [comment]
Inject it into your ctor.

**Comment by CiprianPorumbescu** [comment]
And if I can't do that? Or if I need it anywhere else where I can't inject it into ctor?

**Comment by brockallen** [comment]
IdentityServer is for the most part a closed server. We design for extension via services (that we cover int he docs). To get those services the things they need we do injection. 

Instead of talking about what you can and can't do via the mechanics, how about you tell us what you're tying to do so we can try to provide a suggestion that works with the design.
