### ISSUE TITLE
Open ID Connect and native public app using Thinktecture.IdentityServer.v3

### ISSUE THREAD

**Issue by Harween64** [thinktecture/Thinktecture.IdentityServer.v3#765]
Hi,

We are currently developing a native mobile application, and we need to authorize/authenticate end-user with our identity server (made with thinktecture identity server v3), and/or external social identity providers, to consume some resources in our system.

We are trying to use OIDC flows and specs to obtain access token and id token.
In a perfect world, **we want that native mobile application end-user remains logged indefinitely** (even across native app reboots) until end-user decides to logoff.

So first, we have selected implicit flow. 
But we have discovered that refresh tokens are NOT available in this flow.

 **1) Why implicit flow spec forbids refresh tokens ? where is the danger ?**

**2) To say it in other words, why token endpoint is not “reachable” with implicit flow ?**
(... this two questions are rather for OIDC group but I'm interested in experts answers)

Then, we have tested hybrid flow to obtain refresh tokens (very very long-lived but revocable) and access token (short-lived). 
The problem is to embed a client_secret into a native public client. (bad and insecure practice as described by the OIDC specs)

**3)	So…native public app cannot use hybrid flow…huh?**
(in your hybrid wpf sample, secret is embeded for the demo...but in real life, do native public apps following hybrid flow exist...securely ?)

So, we are currently wondering if a custom code flow solution is a good idea (**noobs inside :)** ):
Make a "proxy"/"front-end" web api  that can reach the token end-point with his own secured client_secret 
and so, relays the code/refresh_token/access_token requests from the native client app to the authorization server token endpoint?

[custom code flow picture][1]

**4)	Any comments about this ?**

  [1]: http://s11.postimg.org/8zotb4uib/code_flow_with_proxy.png

**Comment by leastprivilege** [comment]
Why not simply use long lived access tokens with implicit flow? if using reference tokens - you can also revoke them at any time.

**Comment by leastprivilege** [comment]
..or embed a client secret on the device - nothing is perfect here. And thats by definition.

**Comment by Harween64** [comment]
Thank you for your quick answer.
Implicit flow seems to be a good solution, but I'm not sure of what exactly is reference tokens (don't find anything about this in ODIC or OAuth specs). 
Please, can you explain in few words (or with a link)?
In your implementation, how can we use these reference tokens ?

**Comment by brockallen** [comment]
Check the OAuth2 RFC: http://tools.ietf.org/html/rfc6749

**Comment by leastprivilege** [comment]
another advantage of reference tokens is that you can revoke them centrally.
