### ISSUE TITLE
Redirect to login page from custom service

### ISSUE THREAD

**Issue by mstrong64** [thinktecture/Thinktecture.IdentityServer.v3#766]
I've implemented a custom `IUserService` and in `AuthenticateExternalAsync` I check to see if the `externalUser` has already been attached to a registered user. If not I want to redirect the user back to the login page with a message asking them to login in order to add the external provider to their account.

I'm thinking I need to do something like this:

`return await Task.FromResult<AuthenticateResult>(new AuthenticateResult("/core/login?signin=signInId", externalUser));`

but I don't know how to get `signInId`. Any suggestions?

**Comment by brockallen** [comment]
The signin id is a query string param to the current request. You can access it from the OWIN environment, which is injectable into your user service.

**Comment by brockallen** [comment]
And try this redirect back to login and let me know how it works. If this is a common enough use case, then perhaps we can make an API easier.

The other thought is that your AuthenticateExternal can return an error message saying exactly what you said above, and then IdentityServer will simply show that error message on the login page (so in a sense you'rer already on the login page).

**Comment by mstrong64** [comment]
@brockallen Your last suggestion is a great simple answer. I will give that a go. Thanks!

However, I'm sure I'm going to need that Owin environment at some stage so will I also try that. I may have to come back to you on that one because I'm unsure how to do that, even after reading the DI example.

**Comment by brockallen** [comment]
Just add `OwinEnvironmentService` as a ctor param to your user service and magic will happen.

**Comment by mstrong64** [comment]
Hey magic does happen! I had to separately register my class but it compiles and runs. Nice one!

**Comment by mstrong64** [comment]
So I've implemented your error suggestion and it's perfect. However, I thought I would also try getting the signInId via the Owin context but I couldn't get it to work for now. I looked at how IdSrv is doing it - it includes a call to this:

`private async Task<Microsoft.Owin.Security.AuthenticateResult> GetAuthenticationFrom(string type)`
       ` {`
            `var ctx = Request.GetOwinContext();`
            `var result = await ctx.Authentication.AuthenticateAsync(type);`
           ` return result;`
       ` }`

`ctx` here is `Microsoft.Owin.IOwinContext`, not `OwinEnvironmentService`, so it doesn't compile in my `IUserService`. I had a quick try of this but it didn't work:

`        private async Task<Microsoft.Owin.Security.AuthenticateResult> GetAuthenticationFrom(string type)`
       ` {`
            `  var auth = _owin.Environment.ResolveDependency<Microsoft.Owin.Security.IAuthenticationManager>();`
            `  var result = await auth.AuthenticateAsync(type);`
            `  return result;`
        `}`

`auth` is null. Is there an easier way to do this?

**Comment by brockallen** [comment]
In your code `new` up an `OwinContext` on the `IDictionary<string, object>` that's in the `OwinEnvironmentService`.

**Comment by mstrong64** [comment]
Is this what you meant @brockallen?

`this._owin = owin;`
 `if (!_owin.Environment.ContainsKey("Microsoft.Owin.OwinContext"))`
 `{`
 `_owin.Environment.Add("Microsoft.Owin.OwinContext", new Microsoft.Owin.OwinContext());`
 `}`

When I try to access this using 

`var ctx = _owin.Environment.ResolveDependency<Microsoft.Owin.OwinContext>();`

I get a null returned. In the immediate window I get a message saying:

`The type 'Microsoft.Owin.OwinContext' exists in both 'Microsoft.Owin.dll' and 'Thinktecture.IdentityServer.dll'`

I'm stuck - any pointers?

**Comment by brockallen** [comment]
No I just mean:

```
OwinContext context;
public MyClassCtor(OwinEnvironmentService svc)
{
   this.context = new OwinContext(svc.Environment);
}
```

**Comment by mstrong64** [comment]
Yes! I just found that code in IdSrv AuthenticationController and it seems to be working well. Thanks very much.
