### ISSUE TITLE
Add external logins to existing local login

### ISSUE THREAD

**Issue by scottbrady91** [thinktecture/Thinktecture.IdentityServer.v3#773]
I'm looking to do a similar use case to issue #41, but I'm at a bit of a loss as to where to start.

When the user is logged in I want to offer them the opportunity to assign an external login provider to their account.

Assigning an external login to a local login is simple enough to do from within Identity Server by customising `IUserService`, but I can't figure out how to do it from my external application (acting as an Identity Manager).

Can you point me in the right direction?

Thanks,

Scott.

**Comment by brockallen** [comment]
Well, this is up to your app to do this. While they're logged in locally, redirect the user tot he idp, and when they're redirected back you should have both the local user and external identity. You then do the association in your identity management library.

**Comment by scottbrady91** [comment]
Understood. Thanks!

**Comment by pwnasaur** [comment]
Is there any information on how to do this with a self hosted idp?

**Comment by brockallen** [comment]
It would be no different than an IIS hosted app.
