### ISSUE TITLE
SlidingExpiration set to true not working on idsvr

### ISSUE THREAD

**Issue by tsladev001** [thinktecture/Thinktecture.IdentityServer.v3#774]
I found couple of things on SlidingExpiration: If I just set it true on idsvr(v3) and on RP(UseTokenLifetime, which is true by default), then idsvr SlidingExpiration setting does not work
On RP if I set UseTokenLifetime = false and set some ExpireTimeSpan and SlidingExpiration = true, then it works on RP and it does not call server for login. Can you please verify it?

**Comment by leastprivilege** [comment]
The sliding settings on IdSrv and RP are **unrelated** of course. Nevertheless we will check if sliding works properly in idsrv.

**Comment by brockallen** [comment]
We tested the sliding expiration in IdentityServer and it's working correctly.

As for the sliding in your client app, when you use `UseTokenLifetime` this disables sliding expiration for those cookies and sets the cookie lifetime the same duration as the identity token (5m by default). 

I think you want to to disable `UseTokenLifetime`.

**Comment by tsladev001** [comment]
It is still not working for me. Here is my setting on server: 
CookieAuthenticationOptions.ExpireTimeSpan = 3 min
Client.IdentityTokenLifetime = 3 min
CookieAuthenticationOptions.SlidingExpiration = true

On RP:
OpenIdConnectAuthenticationOptions.UseTokenLifeTime = true;
Not setting any expiry or slidingexpiration on RP

Based on above detail, am I missing anything to test sliding expiration on server?

**Comment by brockallen** [comment]
Are you expecting that when a user is active in the RP that their session in IdentityServer slides?

**Comment by tsladev001** [comment]
Yes.

**Comment by brockallen** [comment]
It's not going to work -- those are two different apps.
