### ISSUE TITLE
View/Reset clients a user has granted consent to? (AllowRememberConsent/model.rememberConsent)

### ISSUE THREAD

**Issue by jameskeongchen** [thinktecture/Thinktecture.IdentityServer.v3#777]
Is there a way for users to view which clients they have granted consent to and/or reset this? I tried clearing all cookies but no longer get prompted for consent since selecting "Remember My Decision".

Where is the rememberConsent stored?

**Comment by leastprivilege** [comment]
Yes - on the permissions page (/permissions)

**Comment by jameskeongchen** [comment]
Ah it persists InMemoryConsentStore.cs - thanks appreciate the really fast reply.
