### ISSUE TITLE
How to Migrate from Identityserver v2 to Identityserver v3

### ISSUE THREAD

**Issue by mbhattar** [thinktecture/Thinktecture.IdentityServer.v3#783]
Currently i am using IdendityServer v2 in my applications, I would like to upgrade it to v3. Do you have any documentation which describes steps for Migrating from v2 to v3. 

Thank you
Murali

**Comment by brockallen** [comment]
No. IdSvr3 is a completely new from scratch (mainly because of the new protocols implemented). As such we don't have any sort of automated migration path.
