### ISSUE TITLE
Question: is it possible to allow any in the client RedirectUris?

### ISSUE THREAD

**Issue by aliwaddell** [thinktecture/Thinktecture.IdentityServer.v3#787]
if i have a dev team of 5 all working on the same project and we have 1 dev idSrv, then i have to set 5 RedirectUris( 1 for each dev ).on the client.
I would like to say "This is a dev server so allow anyone" 

Is it possible? or have i just got it wrong?

**Comment by brockallen** [comment]
You can register multiple redirect URIs for the client application (so one per dev machine). The other approach is that you can configure IdentityServer on each person's dev machine.

**Comment by johnkors** [comment]
Another option is to implement IRedirectUriValidator. Before you do though, read this issue :

https://github.com/thinktecture/Thinktecture.IdentityServer.v3/issues/535#issuecomment-63613355

Maybe only use it in the dev environments.

**Comment by leastprivilege** [comment]
I'd recommend you type in the 5 URLs...
