### ISSUE TITLE
Host Identity Server IIS

### ISSUE THREAD

**Issue by sportingdurutti** [thinktecture/Thinktecture.IdentityServer.v3#788]
Hi i've built the Host Project into IIS Web Site and i can access idsrv using https, but then when requestion https://localhost/idsrv/core/ i get an error Erro HTTP 404.0 - Not Found
Can someone help?

**Comment by brockallen** [comment]
The "welcome" page that you might have seen in the past has come from the hosting project, not from IdentityServer itself. So normally there is no page at the root URL of IdentityServer. Try to visit ~/core/permissions and see what happens.

**Comment by sportingdurutti** [comment]
~/core/permissions gives me the same error. The welcome page is a page from identity server. It's the index.html page

**Comment by brockallen** [comment]
You're confused about the difference between the host and IdentityServer itself. 

As for your 404 -- not sure. I suspect it's how you've configured IIS and the Katana startup.

**Comment by sportingdurutti** [comment]
The host is the host project from https://github.com/thinktecture/Thinktecture.IdentityServer.v3. Is that the correct way to host it on IIS? Which URL can i then use to access Identity Server? Is there also any URL for management?
The 404 , when accessing ~/core/permissions, Katana startup is the one on the Host project, IIS was setup to use SSL

**Comment by leastprivilege** [comment]
No that is the source code version - check the samples repo e.g. the WebHost.

There is no management URL - everything is done in code and the admin UI will take another two/three weeks.

**Comment by sportingdurutti** [comment]
Does that mean that hosting the WebHost version in IIS is enough to start testing the various examples and having a full identity server available ?
The admin UI that will come soon is the same as some of the screenshots that are available from previous version ?
![image](https://cloud.githubusercontent.com/assets/10614576/5833560/81039800-a14c-11e4-8db1-3f0fd6e4c81c.png)
Many Thanks

**Comment by leastprivilege** [comment]
yes - the core repo and the samples are designed to work together.
