### ISSUE TITLE
Url too long on Access token validation endpoint

### ISSUE THREAD

**Issue by remunda** [thinktecture/Thinktecture.IdentityServer.v3#790]
Hello everyone,

When user has longer access token than 2048 characters, IIS return HTTP 404.15. 
This is because validation is done via GET request and access token is send in query string
Can be this switched to POST method, or is it part of OpenId Connect specs?

When i switch to local validation IdSrv freezes, because it can't download /auth/.well-known/openid-configuration. That's probably i have IdSrv and web api that uses oidc in the same application. (IdSrv is mapped to /auth/ path).

Thanks for help
BTW great work! :)

**Comment by brockallen** [comment]
Consider using a reference token, rather than a JWT. See the docs on client configuration.

**Comment by leastprivilege** [comment]
I opened an issue for that - I doubt this will happen before RTM on monday.

**Comment by leastprivilege** [comment]
see #794

**Comment by remunda** [comment]
Thanks, reference tokens works very well :)
