### ISSUE TITLE
Large token - caused "request exceeds the configured maxQueryStringLength"

### ISSUE THREAD

**Issue by aliwaddell** [thinktecture/Thinktecture.IdentityServer.v3#796]
I have some users who have a lot of claims and this in turn generated a large Token and consequently the above message.

The goto fix is to add this to the Identity server. 
Is there a better way?  

system.web
           httpRuntime targetFramework="4.5"  maxQueryStringLength="3000" maxUrlLength="3000"
  
 system.webServer
           requestLimits maxQueryString="3000" maxUrl="3000"
   

Alastair

**Comment by brockallen** [comment]
Consider using a reference token. See the docs for more info.

**Comment by johnkors** [comment]
Also, IE has a maximum of 2000 something odd chars, so setting IIS to 3000 would not help you for IE users.

http://support.microsoft.com/kb/208427

May it rest in peace.
